### ISSUE TITLE
Ошибочное количество баллов за первое задание

### ISSUE THREAD

**Issue by kolonist** [medbar/asr_itmo_practice#1]
Ошибочное количество баллов за первое задание. Указано 7, а должно быть, вроде бы, 8.

Ссылка на код: https://github.com/medbar/asr_itmo_practice/blob/c51717887d118a6281f4784b53ba297fa359620b/asr_lab1.ipynb#L37

**Comment by kolonist** [comment]
МР: https://github.com/medbar/asr_itmo_practice/pull/2

**Comment by medbar** [comment]
Спасибо! 
Закинул 1 балл в бонусы
