### ISSUE TITLE
Вопрос по assert во второй лабораторной

### ISSUE THREAD

**Issue by Geloger37** [medbar/asr_itmo_practice#16]
Я сделал ngram модель и решил ее проверить на assert, но получилась ошибка в 
`assert lm.predict_log_proba(["по-моему"]) > lm.predict_log_proba(["если"])`
Я сделал проверку и на них выдается одинаковый результат логарифма:
![image](https://github.com/medbar/asr_itmo_practice/assets/69764552/f2a9cf39-9bf1-4bf2-8151-5834b0d96cde)
А также вывел построенный счетчик ngram и там оба этих слова появляются с одинаковой частотой:
![image](https://github.com/medbar/asr_itmo_practice/assets/69764552/d8a66385-f60e-4673-91dc-3cdd321d263e)

Хотелось бы задать вопрос, почему логарифмы вероятностей этих нграмм должен быть разным, ведь стоит знак '>'? Или мне необходимо еще раз проверить код?

**Comment by medbar** [comment]
Сравниваются две последовательности
` <s> по-моему </s> `
и 
` <s> если </s>`

Их вероятности не равны, тк order=2
