### ISSUE TITLE
PPL

### ISSUE THREAD

**Issue by Geloger37** [medbar/asr_itmo_practice#17]
Добрый день.
Можно ли, пожалуйста, объяснить каким способом получена перплексия в первом assert для 'ЧТО' равная величине 25.07?

Я пробовал с использованием функции predict_log_proba с различной реализацией chain rule (например, с расчетом первой + последней униграммы + биграммы или расчетом всех униграмм и биграмм) и нормализацией как общей, так и методом среднего геометрического. В данном случае в функции перплексии пробую получать натуральный логарифм для всей последовательности, а потом возводить экспоненту в степень.

Также, попробовал вручную на листочке посчитать различными способами перплексию, в том числе через логарифмы вероятностей или через вероятности напрямую, но ни разу не получилось именно такое значение, получалось 11+, 15+ и 28+ при подгонке.

**Comment by medbar** [comment]
В данном примере "ЧТО" - это Out of Vocabulary слово, то есть языковая модель его не знает. Вероятность для oov слова получается при k=1 сглаживании и размере словаря V=14 получается: 

```
P(['<s>', 'ЧТО', '</s>']) = P( '<s>') * P('ЧТО'| '<s>') * P('</s>'| 'ЧТО') =((3+1)/28 * 1/(3 +14) * 1/(14)) 
```
тогда ppl = 11.854... 
Исправил в мастере + 2 балла за найденный баг
