### ISSUE TITLE
Вопрос по ассерту в test_calculate_ngram_prob()

### ISSUE THREAD

**Issue by kolonist** [medbar/asr_itmo_practice#19]
Здравствуйте!

В функции `test_calculate_ngram_prob()` не могу понять вот этот результат:

```python
counts = count_ngrams(
    [
        'практическое сентября',
        'второе практическое занятие в офлайне 32 сентября в 12 часов 32 минуты',
        'в офлайне в 32 12'
    ],
    order=4
)
assert calculate_ngram_prob(('в', ), counts) == 4/12
```
Почему там получается `4/12`? Ведь 12 - это размер словаря, а нам надо разделить на сумму встречаемостей n-грам.

В нашем тексте есть следующие n-грамы:
```
Look for: ngram = ('в',), count = 4
ngram = ('<s>',), count = 3
ngram = ('практическое',), count = 2
ngram = ('сентября',), count = 2
ngram = ('</s>',), count = 3
ngram = ('второе',), count = 1
ngram = ('занятие',), count = 1
ngram = ('в',), count = 4
ngram = ('офлайне',), count = 2
ngram = ('32',), count = 3
ngram = ('12',), count = 2
ngram = ('часов',), count = 1
ngram = ('минуты',), count = 1
```

И если использовать не количество разных n-грам, а их встречаемость, то получается `0.16`, а не `0.33`.

И в примере [по ссылке](https://cjlise.github.io/machine-learning/N-Gram-Language-Model/), если попробовать код автора на этом тексте, результат так же будет `0.16`, а не `0.33`.

Я где-то ошибаюсь?

**Comment by kolonist** [comment]
В дополнение.

Перплексия тоже не сошлась по тем же причинам.

В [Issue](https://github.com/medbar/asr_itmo_practice/issues/17#issuecomment-1781919791) Вы считаете вероятность одиночной n-грамы `<s>`, как `(3 + 1) / 28`, т.е. в знаменате у Вас тоже `14` - размер словаря, а не встречаемость.

Получается, что если у нас n-грама состоит из однгого элемента, то мы не учитываем встречаемость других слов? Разве тогда не теряется смысл языковой модели? Ведь если у нас текст, допустим `1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1`, то вероятность получить `0` должна быть не `0.5`, а `1 / 23`, разве не так?

**Comment by medbar** [comment]
Добрый день! 
Да, конечно! Вероятность униграмной модели должна быть ровна кол-ву слова поделенному на кол-во всех слов в обучающей выборке. Деление на количество уникальных слов - это ошибка.

**Comment by kolonist** [comment]
Ага, спасибо!

Тогда счас учеру из пул-реквеста со второй лабой подгонку под тест.

**Comment by medbar** [comment]
commit 3d74f8b - исправление тестов

**Comment by medbar** [comment]
Добавил 3 бонусных балла
