### ISSUE TITLE
Лабораторная работа 1. Вопрос по test_wer_per()

### ISSUE THREAD

**Issue by kolonist** [medbar/asr_itmo_practice#3]
Добрый день!

Есть вопрос по корректности теста `test_wer_per()`.

### Тест 1
```
assert_wer_per('привет студент.', 'привет студент',  {
        "wer" : 0,
        "per": 0})
```
Если построить т.н. "выравнивание", то получится следующая ситуация:
```
привет  студент   .
привет  студент  ***
  C        C     D_p
```
То есть, ошибок в словах нет, `wer = 0`, все ОК. 

Однако есть одно удаление в знаках препинания. А т.к. всего знаков препинания `1`, то, казалось бы, `per` должен быть равен `100`?

### Тест 3
```
assert_wer_per('привет студент.', 'привет. студент',  {
        "wer" : 0,
        "per": 100})
```
Опять же, строим "выравнивание":
```
привет  ***  студент   .
привет   .   студент  ***
  C     I_p     C     D_p
```
К `wer` снова нет вопросов, но есть одна вставка и одно удаление в знаках препинания. А т.к. всего знаков препинания `1`, то, казалось бы, `per` здесь должен быть равен `200`?

Возможно, нужно исправить эти 2 теста?

Если же я где-то ошибаюсь в рассуждениях, то прошу подсказать, где именно?

**Comment by medbar** [comment]
Добрый день, @kolonist !
Спасибо за замечания.
Да эти тесты содержат ошибки. Создадите pr с исправлениями?

**Comment by kolonist** [comment]
Да, вечером создам, спасибо!

**Comment by medbar** [comment]
Закинул 2 балла
