### ISSUE TITLE
Final scores

### ISSUE THREAD

**Issue by Geloger37** [medbar/asr_itmo_practice#34]
Добрый день! У меня возник вопрос касательно одной из частей лабораторной работы по курсу распознавание речи. Я, наверное, не слишком хорошо понимаю смысла final_score и как он должен вычисляться. Я по тестам сделал такую реализацию (исключая другие варианты, которые пробовал в процессе):
```
def final_score(self, state_id: int):
        if state_id in self.final_states:
            return 0
        else:
            return float('inf')
```
И в композиции WFST:
```
def final_score(self, state: Tuple[Any]):
        assert len(state) == len(self.wfsts)
        return [fst.final_score(state) for fst, state in zip(self.wfsts, state)]
```
И это прошло все тесты, но я столкнулся в реализации L_WFST с проблемой, что там идет фильтрация как раз по final_score и, вероятно, не только 2 значения должно быть... Я также видел, что в интерфейсе (абстрактном классе) написано о negative log likelihood и попробовал сделать такое:
```
def final_score(self, state_id: int):
        if state_id in self.final_states:
            current_states = [state_id]
            current_log_scores = {state_id: 0.0}
            while current_states:
                print(f'{current_states=}')
                next_states = []
                for current_state in current_states:
                    arcs_container = self.state2arcs[current_state]
                    for arc in arcs_container.arcs():
                        next_state = arc.nextstate
                        transition_weight = arc.weigh
                        log_transition_weight = np.log(transition_weight)
                        log_score_for_transition = current_log_scores[current_state] + log_transition_weight
                        if next_state in self.final_states:
                            current_log_scores[next_state] = log_score_for_transition
                        else:
                            next_states.append(next_state)
                            current_log_scores[next_state] = log_score_for_transition
                current_states = next_states
            return sum(current_log_scores.values())
        else:
            return float('inf')
```
Но не сумел довести до состояния прохождения тестов... В библиотеке openFST не нашел ничего про это, но нашел очень похожее... Вызов функции ShortestPath() и результат выводиться с помощью Weight.Value (также веса могут быть там только 0, 1, inf). Может быть Вы заметите момент, который я неправильно интерпретирую и двигаюсь ли я в правильном направлении?

**Comment by Geloger37** [comment]
Можно ли также попросить объяснить, почему в данном assert, для проверки класса HypothesesKeeper, количество гипотез увеличилось на 1?
```
hyps.append(Hypothesis(11, 0, ['b'], 2))
assert len(hyps) == 2 and hyps.best_state == 1 and hyps.best_score == 10, f"Append doesn't work well"
```

Ведь в условии функции append стоит or:
```
def append(self, hyp: Hypothesis):
        """Append new hyp into collection"""
        if self.is_prunned_by_beam(hyp.score) or self.is_prunned_by_state(hyp.state, hyp.score):
            return
```
В таком случае при score > beam_size (10), то всегда будет выходить из функции без действия и не добавит новый элемент...

**Comment by kolonist** [comment]
Реализация из `final_score` из класса `kenlmLikeWFST` тоже не сильно проясняет картину. В ней мы по заданному стейту считаем `BaseScore`, т.е. `p(word|in_state)`, где word - это "suffix".

Но word в `kenlmLikeWFST` захардкожен как `</s>`, т.е. конец последовательности.

Т.е. получается, что это вероятность (ну в смысле ее логарифм...) придти в состяние `</s>` (т.е. в конечное состояние) из состояния, заданного в аргументе?

**Comment by kolonist** [comment]
В качестве предложения: возможно, в тест `test_OnTheFlyCompose` тоже стоит добавить проверку скора? Тогда проблема с нашими реализациями `final_score` могла бы выявится уже на этом этапе.

<sub>Прошу прощения, что много постов.</sub>

**Comment by medbar** [comment]
final_score - это вес окончания работы в этом стейте. Он или ноль или бесконечность. В openfst он может быть ещё и каким-то числом. В этой работе все упрощённо до только двух значений.

Вес гипотез всегда float, поэтому прикомпозиции надо считать сумму со всех слоев

**Comment by medbar** [comment]
> В качестве предложения: возможно, в тест `test_OnTheFlyCompose` тоже стоит добавить проверку скора? Тогда проблема с нашими реализациями `final_score` могла бы выявится уже на этом этапе.
> 
> <sub>Прошу прощения, что много постов.</sub>

Хорошее предложение. @Geloger37 сможете сделать PR с добавлением этого теста?

**Comment by medbar** [comment]
> Можно ли также попросить, пожалуйста, объяснить, почему в данном assert, для проверки класса HypothesesKeeper, количество гипотез увеличилось на 1?
> 
> ```
> hyps.append(Hypothesis(11, 0, ['b'], 2))
> assert len(hyps) == 2 and hyps.best_state == 1 and hyps.best_score == 10, f"Append doesn't work well"
> ```
> 
> Ведь в условии функции append стоит or:
> 
> ```
> def append(self, hyp: Hypothesis):
>         """Append new hyp into collection"""
>         if self.is_prunned_by_beam(hyp.score) or self.is_prunned_by_state(hyp.state, hyp.score):
>             return
> ```
> 
> В таком случае, при score > beam_size (10), то всегда будет выходить из функции без действия и не добавит новый элемент...

beam_size - это не максимальный вес гипотезы, а максимальное отдаление от наилучшего скора. Наилучший скор - 10. 11 лежит в луче поиска, следовательно добавляем гипотезу.

**Comment by Geloger37** [comment]
Благодарю за ответы! Я добавлю и отправлю PR

**Comment by kolonist** [comment]
Теперь понятно, спасибо!!!
