### ISSUE TITLE
Лабораторная работа 1. Вопрос по test_sawer()

### ISSUE THREAD

**Issue by kolonist** [medbar/asr_itmo_practice#5]
Добрый день!

Дошел до последней части и тоже появился вопрос по тестам `test_sawer()`.
```python
assert_sawer(['привет', 'студент'], ['A', 'A'], ['привет', 'студент'], [1, 2],  {
            "sawer" : 50})
```
`['привет', 'студент']` тут в эталонном и распознанном текстах совпадают, что означает, что до расчета ошибок распознавания спикеров, формула будет выглядеть так:

$$ {0 + 0 + 0 + S_I \over 0 + 0 + 2 + S_I} = {S_I \over 2 + S_I} $$

(очевидно, т.к. I = D = S = 0, C = 2)

В нашем случае, S_I = 1, т.к. возможны 2 варианта мапинга эталонных спикеров на распознанные:
```
Alignment: (1, 2)
Speaker: A, aligned: 1, recognized: 1 => OK
Speaker: A, aligned: 1, recognized: 2 => Error

Alignment: (2, 1)
Speaker: A, aligned: 2, recognized: 1 => Error
Speaker: A, aligned: 2, recognized: 2 => OK
```
Очевидно, что, т.к. эталонный спикер один, а распознано, как будто второе слово произнес второй, у нас в любом случае будет одна ошибка распознавания. Т.е. финальная формула выглядит так:

$$ {S_I \over 2 + S_I} = {1 \over 2 + 1} = {1 \over 3} $$

Т.е. кажется, что `sawer` должен быть равен `33.33(3)`, а не `50`.

**Comment by kolonist** [comment]
Думаю, что тут проблема не в тестах, а в формуле (или в моем понимании этой формулы):

$$ SA{\text -}WER = \min{I + D + S + S_I \over D + S + C + S_I} $$

По ссылке [https://pribor.ifmo.ru/file/article/5994.pdf](https://pribor.ifmo.ru/file/article/5994.pdf), я нашел другую формулу:

$$ SA{\text -}WER = \min{I + D + S + V \over D + S + C} $$

где `V` &mdash; это количество правильно распознанных слов с неверно определенным диктором.

Если считать по ней, то всё сходится, т.к. количество правильно распознанных слов - 2, при этом, в одном из них ошибка, т.е. `V = 1`. И тогда:

$$  0 + V \over 2 = 0 + 1 \over 2  $$

Т.е. выходит, что в знаменателе не должно быть количества ошибок распознавания?

**Comment by kolonist** [comment]
В дополнение. Если считать по формуле с `V`, то все тесты проходят.

**Comment by medbar** [comment]
В этом тесте получается не 2 корректно распознанных слова в знаменателе, а одно. Так как во втором слове ошибка определения диктора. 

Формула  без ошибки Si в знаменателе правильная, если C считается без учёта докторской разметки.

Все зависит от реализации. Главное, чтобы в знаменателе всегда получалось количество слов референса.

**Comment by kolonist** [comment]
А, теперь ясно. Спасибо за разъяснение.
